version: 0.2

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo Entered pre_build phase
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 857407436105.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    on-failure: ABORT
    commands:
      - echo Entered build phase
      - docker buildx create --driver docker-container --use
      # Nginx image
      - docker buildx build \
        --cache-to type=local,dest=cache \
        --cache-from type=local,dest=cache \
        -t 857407436105.dkr.ecr.ap-northeast-1.amazonaws.com/nodejs-codebuild-test-repo:tic-tac-toe
        --load \
        .
      - echo Build completed successfully
  post_build:
    on-failure: ABORT
    commands:
      - echo Entered post_build phase
      - echo Pushing image to Amazon ECR repository
      - docker push 857407436105.dkr.ecr.ap-northeast-1.amazonaws.com/nodejs-codebuild-test-repo:latest
      - echo Logging out from Amazon ECR
      - docker logout

cache:
  paths:
    - 'cache/**/*'