name: Test env workflow

on:
  pull_request:
    branches: ["main"]
    types: [closed]

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Linter code review and Jest jsdom test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get run ID
        id: get-run-id
        uses: actions/github-script@v7
        with:
          script: |
            const runs = await octokit.rest.actions.listWorkflowRuns({
              owner: "cmthPeerapon",
              repo: "tic-tac-toe",
              workflow_id: "test.yml",
              branch: "feature/terraform",
              event: "pull_request",
              status: "success",
              per-page: 5
            });

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: build/
          run-id: ${{ steps.get-run-id.outputs.result }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync build/ s3://${{ vars.S3_BUCKET }} --delete
