name: Deploy Workflow

on:
  push:
    branches: main

env:
  AWS_REGION: "ap-southeast-1"

permissions:
  id-token: write
  contents: read

jobs:
  DeployAppOnEc2:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: AssumeRoleAndCallIdentity
        id: print-to-log
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::857407436105:role/peerapon-ghwf-as-codedeploy
          role-session-name: peerapon-ghwf-as-codedeploy
          aws-region: ${{ env.AWS_REGION }}
      - name: Sts GetCallerIdentity
        run: aws sts get-caller-identity
