name: Test Workflow

on:
  push:
    branches:
      - "**"

jobs:
  RunTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install modules
        run: npm i
      - name: Lint Test
        run: npm run lint
