name: Test env workflow

on:
  pull_request:
    branches:
      - "feature/**"

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  Test:
    name: Linter code review and Jest jsdom test
    runs-on: ubuntu-latest
    outputs:
      linter_result: ${{ steps.linter_code_review.outputs.result }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install modules
        run: npm ci

      - name: Linter code review
        id: linter_code_review
        run: npm run lint

      - name: Jest jsdom test
        run: npm run jest
  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.REPO_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
