name: Test env workflow

on:
  pull_request:
    branches:
      - "feature/**"

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  Test:
    name: Linter code review and Jest jsdom test
    runs-on: ubuntu-latest
    outputs:
      linter_result: ${{ steps.linter_code_review.outputs.result }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install modules
        run: npm ci

      - name: Linter code review
        id: linter_code_review
        run: npm run lint

      - name: Run unit tests
        run: npm run jest:unit

      - name: Run integration tests
        run: npm run jest:integration

  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Build app
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: build/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync build/ s3://${{ vars.S3_BUCKET }} --delete
